spring.application.name=RTFM

spring.ai.model.embedding=ollama
spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=llama3.2
spring.ai.ollama.embedding.options.model=qwen3-embedding:0.6b

spring.ai.google.genai.project-id=gen-lang-client-0307111228
# spring.ai.google.genai.location=${GOOGLE_CLOUD_LOCATION}
spring.ai.google.genai.location=global
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite-preview
spring.ai.google.genai.api-key=
#brave.api.key=

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=3MB

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.username=default
spring.data.redis.password=abdev
redis.session.chat.ttl=24

rag.similarity.treshold=0.95
